# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Dockerfile for AgentOps MCP Server

FROM node:lts-alpine AS builder
WORKDIR /app

# Install dependencies and build
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src
RUN npm install --ignore-scripts && npm run build

# Production image
FROM node:lts-alpine
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY README.md ./README.md

ENV NODE_ENV=production
ENTRYPOINT ["node", "dist/server.js"]
